### ISSUE TITLE
Possible bug while initailizing dependency in initRenderPass function

### ISSUE THREAD

**Issue by bonohub13** [baeng72/Vulkan-RTIOW#1]
While initializing `dependency` in `initRenderPass`, `dependency.srcStageMask` is initialized twice instead of initializing `VkSubpassDependency.dstAccessMask`

Actual code:
``` rust
VkRenderPass initRenderPass(VkDevice device, VkFormat colorFormat) {
// ...
	VkSubpassDependency dependency{};
	dependency.srcSubpass = VK_SUBPASS_EXTERNAL;
	dependency.dstSubpass = 0;
	dependency.srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
	dependency.dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
	dependency.srcAccessMask = 0;
	dependency.dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
// ...
}
```

**Comment by bonohub13** [comment]
The fix might be to initialize `VkSubpassDependency.dstAccessMask` with `VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT`.
I am currently doing a rewrite to learn ray tracing using your code with Rust and Ash (Vulkan binding). (I know, how original...)
And the above mentioned initialization did compile and the render pass did initialize without any issue so it should be fine.

**Comment by baeng72** [comment]
Hey Thanks for the heads-up!
I'll update when I get a moment.
I'm glad you're finding some use for my code!
There will certainly be bugs in my code. :)
Thanks Brian.

**Comment by baeng72** [comment]
I've updated the existing code and added code for the Chapter 6 normals example.
The interesting part of the code is really just the compute shader. 
I think a general purpose ray tracer would need to have test for hitting a triangle, and then pass objects made of triangles in buffers and hit test those triangles. 
There is a ray-tracing pipeline in Vulkan, but my graphics card doesn't support it, so I do it manually.
